package com.anhduc.backend.enums;

public enum PermissionType {
    CREATE_USER, READ_USER, UPDATE_USER, DELETE_USER,
    CREATE_STORE, READ_STORE, UPDATE_STORE, DELETE_STORE,
    CREATE_MATERIAL, READ_MATERIAL, UPDATE_MATERIAL, DELETE_MATERIAL,
    VIEW_INVENTORY, MANAGE_INVENTORY,
    VIEW_SALES, MANAGE_SALES
}