

spring:
  datasource:
    username: root
    url: "jdbc:mysql://localhost:3306/lacoste?createDatabaseIfNotExist=true"
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

