spring:
  datasource:
    url: jdbc:mysql://cmms-db.mysql.database.azure.com:3306/cmms?createDatabaseIfNotExist=true
    username: cmms
    password: Anhduc120101
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

cloud:
  aws:
    credentials:
      accessKey: AKIA4MTWL3ET3M4ZYFYP
      secretKey: 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
    region:
      static: ap-southeast-1
    s3:
      bucket-name: mutantorchid

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  tokenExpiryTime: 3600 #in seco
  refreshTokenExpiration: 36000
  refreshable-duration: 36000 # in seconds

oauth2:
  google:
    client-id: "229203659707-kpvju7vl0mpc0j4gnd2s5eiclnuoaf6q.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "https://cmms-cyan.vercel.app"

PAYOS_CLIENT_ID: e358e1d6-1166-41f2-ad96-a4d903d281fa
PAYOS_API_KEY: 6bcd54c7-9652-4928-8003-22a247c10572
PAYOS_CHECKSUM_KEY: ece006721f5cacdbe5f7a4b05715e915462b20251670a8e3c6ead9464b694e20

openai:
  api:
    key: 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
